"""empty message

Revision ID: 581f2e8c70ec
Revises: 6be50b3ab5a4
Create Date: 2021-06-11 19:51:57.528676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581f2e8c70ec'
down_revision = '6be50b3ab5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
